export const hotelPageFixtures = {
  storeId: 'store-e2e-demo',
  access: {
    ok: true,
    message: '',
  },
  user: {
    id: 'user-e2e-owner',
  },
  membership: {
    role: 'owner',
  },
  stays: [
    {
      id: 'stay-001',
      stay_code: 'HT-20260316-001',
      status: 'checked_in',
      customer_id: 'customer-001',
      pet_id: 'pet-001',
      planned_check_in_at: '2026-03-16T01:00:00.000Z',
      planned_check_out_at: '2026-03-17T01:00:00.000Z',
      actual_check_in_at: '2026-03-16T01:10:00.000Z',
      actual_check_out_at: null,
      nights: 1,
      pickup_required: true,
      dropoff_required: false,
      vaccine_expires_on: '2026-04-10',
      total_amount_jpy: 8800,
      notes: '臆病なので個室優先',
    },
    {
      id: 'stay-002',
      stay_code: 'HT-20260317-002',
      status: 'reserved',
      customer_id: 'customer-002',
      pet_id: 'pet-002',
      planned_check_in_at: '2026-03-17T03:00:00.000Z',
      planned_check_out_at: '2026-03-17T09:00:00.000Z',
      actual_check_in_at: null,
      actual_check_out_at: null,
      nights: 1,
      pickup_required: false,
      dropoff_required: true,
      vaccine_expires_on: null,
      total_amount_jpy: 4500,
      notes: null,
    },
  ],
  stayItems: [
    {
      id: 'stay-item-001',
      stay_id: 'stay-001',
      menu_item_id: 'menu-001',
      item_type: 'overnight',
      label_snapshot: '宿泊 基本料金',
      billing_unit_snapshot: 'per_night',
      quantity: 1,
      unit_price_snapshot: 6800,
      line_amount_jpy: 6800,
      counts_toward_capacity: true,
      sort_order: 10,
      notes: null,
    },
    {
      id: 'stay-item-002',
      stay_id: 'stay-001',
      menu_item_id: 'menu-003',
      item_type: 'transport',
      label_snapshot: '送迎',
      billing_unit_snapshot: 'fixed',
      quantity: 1,
      unit_price_snapshot: 2000,
      line_amount_jpy: 2000,
      counts_toward_capacity: false,
      sort_order: 20,
      notes: '片道',
    },
  ],
  customers: [
    { id: 'customer-001', full_name: '山田 花子' },
    { id: 'customer-002', full_name: '鈴木 一郎' },
  ],
  pets: [
    { id: 'pet-001', name: 'モカ', customer_id: 'customer-001' },
    { id: 'pet-002', name: 'レオ', customer_id: 'customer-002' },
  ],
  menuItems: [
    {
      id: 'menu-001',
      name: '宿泊 基本料金',
      item_type: 'overnight',
      billing_unit: 'per_night',
      duration_minutes: null,
      default_quantity: 1,
      price: 6800,
      tax_rate: 0.1,
      tax_included: true,
      counts_toward_capacity: true,
      is_active: true,
      display_order: 10,
      notes: '小型犬向け',
    },
    {
      id: 'menu-002',
      name: 'ハイシーズン加算',
      item_type: 'option',
      billing_unit: 'fixed',
      duration_minutes: null,
      default_quantity: 1,
      price: 1500,
      tax_rate: 0.1,
      tax_included: true,
      counts_toward_capacity: false,
      is_active: false,
      display_order: 320,
      notes: 'GW・年末年始',
    },
    {
      id: 'menu-003',
      name: '送迎',
      item_type: 'transport',
      billing_unit: 'fixed',
      duration_minutes: null,
      default_quantity: 1,
      price: 2000,
      tax_rate: 0.1,
      tax_included: true,
      counts_toward_capacity: false,
      is_active: true,
      display_order: 30,
      notes: '片道2km圏内',
    },
  ],
  settings: {
    id: 'hotel-settings-001',
    store_id: 'store-e2e-demo',
    max_concurrent_pets: 4,
    calendar_open_hour: 8,
    calendar_close_hour: 21,
  },
} as const
