export const inventoryPageFixtures = {
  storeId: 'store-e2e-demo',
  dashboardNowIso: '2026-03-16T03:00:00.000Z',
  dashboardItems: [
    { id: 'item-001', name: 'トリートメント剤', unit: '本', optimal_stock: 12 },
    { id: 'item-002', name: 'デンタルガム', unit: '袋', optimal_stock: 8 },
    { id: 'item-003', name: 'ホテル用シーツ', unit: '枚', optimal_stock: 40 },
  ],
  dashboardMovements: [
    {
      item_id: 'item-001',
      movement_type: 'inbound',
      quantity_delta: 5,
      expires_on: '2026-03-25',
      happened_at: '2026-03-16T01:00:00.000Z',
    },
    {
      item_id: 'item-001',
      movement_type: 'outbound',
      quantity_delta: -3,
      expires_on: '2026-03-25',
      happened_at: '2026-03-16T02:00:00.000Z',
    },
    {
      item_id: 'item-002',
      movement_type: 'inbound',
      quantity_delta: 2,
      expires_on: '2026-03-18',
      happened_at: '2026-03-16T01:30:00.000Z',
    },
    {
      item_id: 'item-002',
      movement_type: 'outbound',
      quantity_delta: -1,
      expires_on: '2026-03-18',
      happened_at: '2026-03-16T02:30:00.000Z',
    },
    {
      item_id: 'item-003',
      movement_type: 'inbound',
      quantity_delta: 30,
      expires_on: null,
      happened_at: '2026-03-15T03:00:00.000Z',
    },
    {
      item_id: 'item-004',
      movement_type: 'outbound',
      quantity_delta: -5,
      expires_on: null,
      happened_at: '2026-03-14T04:00:00.000Z',
    },
  ],
  reorderSuggestions: [
    {
      item_id: 'item-001',
      item_name: 'トリートメント剤',
      category: 'ケア用品',
      unit: '本',
      supplier_name: 'トリマー商会',
      current_stock: 2,
      reorder_point: 6,
      optimal_stock: 12,
      minimum_order_quantity: 4,
      order_lot_size: 2,
      lead_time_days: 3,
      last_inbound_unit_cost: 850,
      recommended_quantity: 10,
      priority_rank: 1,
    },
    {
      item_id: 'item-002',
      item_name: 'デンタルガム',
      category: '物販',
      unit: '袋',
      supplier_name: 'ペット物販センター',
      current_stock: 1,
      reorder_point: 4,
      optimal_stock: 8,
      minimum_order_quantity: 2,
      order_lot_size: 1,
      lead_time_days: 2,
      last_inbound_unit_cost: 320,
      recommended_quantity: 7,
      priority_rank: 3,
    },
    {
      item_id: 'item-003',
      item_name: 'ホテル用シーツ',
      category: 'ホテル',
      unit: '枚',
      supplier_name: 'トリマー商会',
      current_stock: 30,
      reorder_point: 10,
      optimal_stock: 40,
      minimum_order_quantity: 10,
      order_lot_size: 10,
      lead_time_days: 5,
      last_inbound_unit_cost: 90,
      recommended_quantity: 10,
      priority_rank: 7,
    },
  ],
  productItems: [
    {
      id: 'item-001',
      name: 'トリートメント剤',
      category: 'ケア用品',
      unit: '本',
      supplier_name: 'トリマー商会',
      jan_code: '4900000000012',
      optimal_stock: 12,
      reorder_point: 6,
      lead_time_days: 3,
      preferred_supplier_name: 'トリマー商会 本店',
      minimum_order_quantity: 4,
      order_lot_size: 2,
      is_active: true,
      notes: '皮膚が弱い子向け',
    },
    {
      id: 'item-002',
      name: 'デンタルガム',
      category: null,
      unit: '袋',
      supplier_name: null,
      jan_code: null,
      optimal_stock: 8,
      reorder_point: 4,
      lead_time_days: 2,
      preferred_supplier_name: null,
      minimum_order_quantity: 2,
      order_lot_size: 1,
      is_active: false,
      notes: null,
    },
    {
      id: 'item-003',
      name: 'ホテル用シーツ',
      category: 'ホテル',
      unit: '枚',
      supplier_name: 'トリマー商会',
      jan_code: '4900000000036',
      optimal_stock: 40,
      reorder_point: 10,
      lead_time_days: 5,
      preferred_supplier_name: 'トリマー商会',
      minimum_order_quantity: 10,
      order_lot_size: 10,
      is_active: true,
      notes: 'ホテル宿泊用',
    },
    {
      id: 'item-004',
      name: '肉球クリーム',
      category: 'ケア用品',
      unit: '個',
      supplier_name: 'ケア卸センター',
      jan_code: '4900000000043',
      optimal_stock: 5,
      reorder_point: 2,
      lead_time_days: 4,
      preferred_supplier_name: 'ケア卸センター',
      minimum_order_quantity: 1,
      order_lot_size: 1,
      is_active: true,
      notes: '冬場に売れやすい',
    },
  ],
  historyRows: [
    {
      id: 'movement-001',
      movement_type: 'outbound',
      quantity_delta: -3,
      reason: 'トリミング施術で消費',
      happened_at: '2026-03-16T02:00:00.000Z',
      inventory_items: { name: 'トリートメント剤', unit: '本' },
    },
    {
      id: 'movement-002',
      movement_type: 'inbound',
      quantity_delta: 2,
      reason: null,
      happened_at: '2026-03-16T01:30:00.000Z',
      inventory_items: { name: 'デンタルガム', unit: '袋' },
    },
    {
      id: 'movement-003',
      movement_type: 'stocktake_adjustment',
      quantity_delta: -1,
      reason: '棚卸差異',
      happened_at: '2026-03-15T09:00:00.000Z',
      inventory_items: null,
    },
  ],
  inboundItems: [
    { id: 'item-001', name: 'トリートメント剤', unit: '本' },
    { id: 'item-003', name: 'ホテル用シーツ', unit: '枚' },
    { id: 'item-004', name: '肉球クリーム', unit: '個' },
  ],
  inboundRows: [
    {
      id: 'inbound-001',
      quantity_delta: 12,
      unit_cost: 850,
      reason: '定期仕入れ',
      lot_number: 'LOT-TR-202603',
      expires_on: '2026-09-30',
      happened_at: '2026-03-16T00:30:00.000Z',
      inventory_items: { name: 'トリートメント剤', unit: '本' },
    },
    {
      id: 'inbound-002',
      quantity_delta: 20,
      unit_cost: null,
      reason: null,
      lot_number: null,
      expires_on: null,
      happened_at: '2026-03-15T06:00:00.000Z',
      inventory_items: { name: 'ホテル用シーツ', unit: '枚' },
    },
  ],
  outboundItems: [
    { id: 'item-001', name: 'トリートメント剤', unit: '本' },
    { id: 'item-004', name: '肉球クリーム', unit: '個' },
  ],
  outboundRows: [
    {
      id: 'outbound-001',
      quantity_delta: -2,
      reason: '施術利用',
      happened_at: '2026-03-16T02:10:00.000Z',
      inventory_items: { name: 'トリートメント剤', unit: '本' },
    },
    {
      id: 'outbound-002',
      quantity_delta: -1,
      reason: null,
      happened_at: '2026-03-15T08:00:00.000Z',
      inventory_items: { name: '肉球クリーム', unit: '個' },
    },
  ],
  purchaseOrderItems: [
    { id: 'item-001', name: 'トリートメント剤', unit: '本' },
    { id: 'item-003', name: 'ホテル用シーツ', unit: '枚' },
  ],
  purchaseOrders: [
    {
      id: 'po-001',
      order_no: 'PO-20260316-001',
      supplier_name: 'トリマー商会',
      status: 'draft',
      ordered_on: '2026-03-16',
      expected_on: '2026-03-20',
      total_amount: 10200,
      notes: '欠品対策の前倒し発注',
      inventory_purchase_order_items: [
        {
          id: 'po-line-001',
          item_name: 'トリートメント剤',
          quantity: 10,
          unit_cost: 850,
          notes: null,
        },
        {
          id: 'po-line-002',
          item_name: 'ホテル用シーツ',
          quantity: 20,
          unit_cost: 85,
          notes: 'ホテル繁忙期向け',
        },
      ],
    },
    {
      id: 'po-002',
      order_no: 'PO-20260312-002',
      supplier_name: 'ケア卸センター',
      status: 'received',
      ordered_on: '2026-03-12',
      expected_on: null,
      total_amount: 2400,
      notes: null,
      inventory_purchase_order_items: [],
    },
  ],
  stocktakeRows: [
    {
      id: 'stocktake-001',
      item_id: 'item-001',
      quantity_delta: -1,
      reason: '棚卸差異',
      happened_at: '2026-03-16T03:30:00.000Z',
      inventory_items: { name: 'トリートメント剤', unit: '本' },
    },
    {
      id: 'stocktake-002',
      item_id: 'item-004',
      quantity_delta: 2,
      reason: '倉庫在庫を反映',
      happened_at: '2026-03-15T04:00:00.000Z',
      inventory_items: { name: '肉球クリーム', unit: '個' },
    },
  ],
} as const
