export const paymentsPageFixtures = {
  storeId: 'store-e2e-demo',
  payments: [
    {
      id: 'payment-001',
      appointment_id: 'appt-001',
      customer_id: 'customer-001',
      visit_id: 'visit-001',
      status: '支払済',
      method: 'カード',
      subtotal_amount: 8000,
      tax_amount: 800,
      discount_amount: 300,
      total_amount: 8500,
      paid_at: '2026-03-16T03:30:00.000Z',
      notes: '次回予約で毛玉取り提案',
      customers: [{ full_name: '山田 花子' }],
      appointments: [{ id: 'appt-001' }],
    },
    {
      id: 'payment-002',
      appointment_id: 'appt-002',
      customer_id: 'customer-002',
      visit_id: null,
      status: '未会計',
      method: null,
      subtotal_amount: 2500,
      tax_amount: 250,
      discount_amount: 0,
      total_amount: 2750,
      paid_at: null,
      notes: null,
      customers: null,
      appointments: [{ id: 'appt-002' }],
    },
  ],
  appointments: [
    {
      id: 'appt-001',
      customer_id: 'customer-001',
      start_time: '2026-03-16T01:00:00.000Z',
      customers: [{ full_name: '山田 花子' }],
      pets: [{ name: 'こむぎ' }],
    },
    {
      id: 'appt-002',
      customer_id: 'customer-002',
      start_time: '2026-03-16T04:00:00.000Z',
      customers: null,
      pets: null,
    },
    {
      id: 'appt-003',
      customer_id: 'customer-001',
      start_time: '2026-03-17T01:00:00.000Z',
      customers: [{ full_name: '山田 花子' }],
      pets: [{ name: 'モカ' }],
    },
  ],
  appointmentMenus: [
    { id: 'am-001', appointment_id: 'appt-001', menu_name: 'トリミングコース', price: 8800, tax_rate: 0.1, tax_included: true },
    { id: 'am-002', appointment_id: 'appt-002', menu_name: 'シャンプーコース', price: 2750, tax_rate: 0.1, tax_included: true },
    { id: 'am-003', appointment_id: 'appt-003', menu_name: 'カットコース', price: 5500, tax_rate: 0.1, tax_included: true },
    { id: 'am-004', appointment_id: 'appt-003', menu_name: '爪切り', price: 1200, tax_rate: 0.1, tax_included: true },
  ],
  hotelStaysForPos: [
    { id: 'stay-001', appointment_id: 'appt-001' },
    { id: 'stay-002', appointment_id: 'appt-003' },
  ],
  hotelChargesForPos: [
    { id: 'hc-001', stay_id: 'stay-001', label: '1泊', line_amount_jpy: 4000, tax_rate: 0.1, tax_included: true },
    { id: 'hc-002', stay_id: 'stay-001', label: '送迎', line_amount_jpy: 1000, tax_rate: 0.1, tax_included: true },
  ],
  receiptAppointmentMenus: [
    { appointment_id: 'appt-001', menu_name: 'トリミングコース', price: 6800, duration: 120 },
    { appointment_id: 'appt-001', menu_name: '毛玉取り', price: 2000, duration: 20 },
  ],
  customers: [
    { id: 'customer-001', full_name: '山田 花子' },
    { id: 'customer-002', full_name: '佐々木 次郎' },
  ],
} as const
