export const serviceMenusPageFixtures = {
  storeId: 'store-e2e-demo',
  menus: [
    {
      id: 'menu-001',
      name: 'シャンプーコース',
      category: 'トリミング',
      price: 8500,
      duration: 90,
      tax_rate: 0.1,
      tax_included: true,
      is_active: true,
      is_instant_bookable: true,
      display_order: 1,
      notes: '毛玉が多い場合は追加料金',
    },
    {
      id: 'menu-002',
      name: '毛玉取り',
      category: null,
      price: 1200,
      duration: 20,
      tax_rate: null,
      tax_included: null,
      is_active: null,
      is_instant_bookable: null,
      display_order: null,
      notes: '',
    },
  ],
  completedAppointments: [
    { menu: 'シャンプーコース', duration: 120 },
    { menu: 'シャンプーコース', duration: 120 },
    { menu: 'シャンプーコース', duration: 110 },
    { menu: 'シャンプーコース', duration: 120 },
    { menu: 'シャンプーコース', duration: 110 },
    { menu: '毛玉取り', duration: 20 },
  ],
} as const
