export const settingsPageFixtures = {
  storeId: 'store-e2e-demo',
  storageGuard: {
    ok: true,
    message: '',
    storeId: 'store-e2e-demo',
    user: { id: 'user-owner-001' },
  },
  manageState: {
    currentRole: 'admin',
    canManage: true,
    label: 'あり（owner/admin）',
  },
  notificationAccess: {
    ok: true,
    message: '',
    state: {
      notificationOptionEnabled: true,
    },
  },
  notificationSettings: {
    reminder_line_enabled: null,
    reminder_email_enabled: false,
    reminder_day_before_enabled: true,
    reminder_same_day_enabled: null,
    reminder_day_before_send_hour_jst: 25,
    reminder_same_day_send_hour_jst: -1,
    followup_line_enabled: true,
    followup_days: [90, 30, 400, 30],
    slot_reoffer_line_enabled: null,
    monthly_message_limit: null,
    monthly_message_limit_with_option: 9999999,
    over_limit_behavior: null,
  },
  publicReserveSettings: {
    public_reserve_conflict_warn_threshold_percent: 12,
    public_reserve_staff_bias_warn_threshold_percent: 80,
    public_reserve_slot_days: 5,
    public_reserve_slot_interval_minutes: 30,
    public_reserve_slot_buffer_minutes: 20,
    public_reserve_business_start_hour_jst: 9,
    public_reserve_business_end_hour_jst: 19,
    public_reserve_min_lead_minutes: 120,
    member_card_rank_visible: true,
    member_portal_ttl_days: 90,
    ltv_gold_annual_sales_threshold: 120000,
    ltv_silver_annual_sales_threshold: 60000,
    ltv_bronze_annual_sales_threshold: 30000,
    ltv_gold_visit_count_threshold: 12,
    ltv_silver_visit_count_threshold: 6,
    ltv_bronze_visit_count_threshold: 3,
  },
  blockedDates: [{ date_key: '2026-03-20' }, { date_key: '2026-03-21' }],
  customerManagementSettings: {
    medical_record_list_limit: 12,
    journal_visibility_mode: 'include_drafts',
    calendar_expand_out_of_range_appointments: false,
  },
  storageQuota: {
    storeId: 'store-e2e-demo',
    planCode: 'standard',
    policy: 'cleanup_orphans',
    usageBytes: 9_126_805_504,
    baseLimitBytes: 10_737_418_240,
    extraCapacityBytes: 2_147_483_648,
    customLimitBytes: null,
    totalLimitBytes: 12_884_901_888,
    usageWarning: '使用量の取得に失敗したため、暫定値を表示しています: Bad Gateway',
  },
} as const
